/**
 * Place Layout Validator
 *
 * Validates that all places have a layout generated and objects created.
 * This ensures places are ready for player exploration with:
 * - Tilemap data for rendering
 * - Object entities for furniture, decorations, and exits
 *
 * Key validation rules:
 * 1. All places must have a layout file
 * 2. Places with defined functional types should have objects
 *
 * Repair: Generates layout and objects using the place layout generator.
 * Layout generation is part of place generation, not on-demand.
 */

import type { BaseEntity } from '@dmnpc/types/entity';
import { isPlace } from '@dmnpc/core/entities/type-guards.js';
import type { Validator, ValidationIssue, ValidationContext } from '../integrity-types.js';
import { layoutExists } from '@dmnpc/core/universe/universe-store.js';

/**
 * Place Layout Validator
 *
 * Validates that feet-scale places have layouts and objects.
 * Layouts are generated during place validation/repair, not on-demand.
 */
export const placeLayoutValidator: Validator = {
  id: 'place-layout',
  name: 'Place Layout Validator',

  validate(entity: BaseEntity, ctx: ValidationContext): ValidationIssue[] {
    // Only validate places
    if (!entity.id.startsWith('PLACE_')) {
      return [];
    }

    if (!isPlace(entity)) return [];
    const place = entity;
    const issues: ValidationIssue[] = [];

    // Skip the abstract cosmos root
    if (place.id === 'PLACE_the_cosmos') {
      return [];
    }

    // All places need layouts now (for exits and tiles)
    const universeId = ctx.universe.id;

    // Rule 1: Check if layout exists - this is an error, not a warning
    const hasLayout = layoutExists(universeId, place.id);
    if (!hasLayout) {
      issues.push({
        entityId: place.id,
        entityType: 'place',
        validatorId: 'place-layout',
        severity: 'error',
        field: 'layout',
        message: `Place is missing layout. Run repair to generate layout and objects.`,
        suggestedFix: {
          field: 'layout',
          value: null, // Layout will be generated by repair
          confidence: 'high',
          method: 'layout',
        },
      });
    }

    // Rule 2: Check if place has objects
    const placeObjects = Array.from(ctx.objects.values()).filter(
      (obj) => obj.position.parent === place.id,
    );

    if (placeObjects.length === 0 && hasLayout) {
      // Place has layout but no objects - this indicates a stale layout
      issues.push({
        entityId: place.id,
        entityType: 'place',
        validatorId: 'place-layout',
        severity: 'warning',
        field: 'objects',
        message: `Place has layout but no objects. Run repair to regenerate layout with objects.`,
        suggestedFix: {
          field: 'objects', // Indicates this is an objects issue, not missing layout
          value: null, // Layout will be regenerated by repair
          confidence: 'high',
          method: 'layout',
        },
      });
    }

    return issues;
  },
};
