/**
 * Vessel Crew Consistency Validator
 *
 * Validates that vessels have proper crew configuration:
 * - Vessels have crew members (characters with work location on vessel)
 * - Vessels have a captain (crew member with TAG_captain)
 * - Crew schedules provide 24/7 helm coverage
 *
 * Note: Controls location defaults to vessel root if no TAG_workplace_vessel_controls place exists.
 *
 * Repair: LLM-based - generates missing crew members with appropriate routines.
 */

import type { BaseEntity, Place } from '@dmnpc/types/entity';
import type { TimePeriod } from '@dmnpc/types/npc';
import { isPlace } from '@dmnpc/core/entities/type-guards.js';
import type { Validator, ValidationIssue, ValidationContext } from '../integrity-types.js';

/**
 * Check if a place is a vessel by looking for a vessel_helm object in that place.
 * Uses ValidationContext (not UniverseContext) for object lookup.
 */
function isVesselPlace(placeId: string, ctx: ValidationContext): boolean {
  for (const [, obj] of ctx.objects) {
    if (obj.position.parent === placeId && obj.info.purpose === 'vessel_helm') return true;
  }
  return false;
}

/**
 * Check if a place is a descendant of another place.
 * Simplified version for validator context (uses Map-based places).
 */
function isDescendantOfValidation(
  placeId: string,
  ancestorId: string,
  places: Map<string, Place>,
): boolean {
  let currentId: string | null = placeId;
  const visited = new Set<string>();

  while (currentId) {
    if (visited.has(currentId)) return false; // Cycle detection
    visited.add(currentId);

    const place = places.get(currentId);
    if (!place) return false;

    if (place.position.parent === ancestorId) return true;
    currentId = place.position.parent;
  }

  return false;
}

/**
 * Get vessel crew from validation context.
 */
function getVesselCrewFromContext(vesselId: string, ctx: ValidationContext): string[] {
  const crewIds: string[] = [];

  for (const [charId, char] of ctx.characters) {
    // Check if work location is on this vessel
    const workPlaceId = char.info.routine?.work?.placeId;
    if (workPlaceId && isDescendantOfValidation(workPlaceId, vesselId, ctx.places)) {
      crewIds.push(charId);
      continue;
    }

    // Check if character has crew purpose AND home is on vessel
    const isCrewPurpose = char.info.purpose === 'captain' || char.info.purpose === 'helmsman';
    const homePlaceId = char.info.routine?.home.placeId;
    if (
      isCrewPurpose &&
      homePlaceId &&
      isDescendantOfValidation(homePlaceId, vesselId, ctx.places)
    ) {
      crewIds.push(charId);
    }
  }

  return crewIds;
}

/**
 * Validate vessel crew configuration.
 */
function validateVesselCrew(place: Place, ctx: ValidationContext): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  // Only validate vessels (identified by vessel_helm object)
  if (!isVesselPlace(place.id, ctx)) {
    return issues;
  }

  // Check 1: Vessel has no crew
  const crewIds = getVesselCrewFromContext(place.id, ctx);
  if (crewIds.length === 0) {
    issues.push({
      entityId: place.id,
      entityType: 'place',
      validatorId: 'vessel-crew-consistency',
      severity: 'error',
      field: 'crew',
      message: `Vessel ${place.label} has no crew members`,
      suggestedFix: {
        field: 'crew',
        value: null, // Will be generated by repair
        confidence: 'medium',
        method: 'llm',
      },
    });
    return issues; // Can't check other issues without crew
  }

  // Check 2: Vessel has no captain
  let hasCaptain = false;
  for (const charId of crewIds) {
    const char = ctx.characters.get(charId);
    if (char?.info.purpose === 'captain') {
      hasCaptain = true;
      break;
    }
  }

  if (!hasCaptain) {
    issues.push({
      entityId: place.id,
      entityType: 'place',
      validatorId: 'vessel-crew-consistency',
      severity: 'error',
      field: 'crew',
      message: `Vessel ${place.label} has crew but no captain`,
      suggestedFix: {
        field: 'crew',
        value: null,
        confidence: 'medium',
        method: 'llm',
      },
    });
  }

  // Check 3: Crew schedules don't provide 24/7 coverage
  if (crewIds.length > 0) {
    const timePeriods: TimePeriod[] = ['dawn', 'morning', 'afternoon', 'evening', 'night'];
    const coveredPeriods = new Set<TimePeriod>();

    for (const charId of crewIds) {
      const member = ctx.characters.get(charId);
      if (!member) continue;

      const canHelm = member.info.purpose === 'captain' || member.info.purpose === 'helmsman';
      if (!canHelm) continue;

      const schedule = member.info.routine?.schedule;
      if (!schedule) continue;

      for (const period of timePeriods) {
        if (schedule[period] === 'work') {
          coveredPeriods.add(period);
        }
      }
    }

    if (coveredPeriods.size < 5) {
      const missingPeriods = timePeriods.filter((p) => !coveredPeriods.has(p));
      issues.push({
        entityId: place.id,
        entityType: 'place',
        validatorId: 'vessel-crew-consistency',
        severity: 'warning',
        field: 'crew',
        message: `Vessel ${place.label} crew schedules don't provide 24/7 helm coverage (missing: ${missingPeriods.join(', ')})`,
        suggestedFix: {
          field: 'crew',
          value: null,
          confidence: 'medium',
          method: 'llm',
        },
      });
    }
  }

  return issues;
}

/**
 * Vessel Crew Consistency Validator
 *
 * Checks that vessels have proper crew configuration with 24/7 helm coverage.
 */
export const vesselCrewConsistencyValidator: Validator = {
  id: 'vessel-crew-consistency',
  name: 'Vessel Crew Consistency Validator',

  validate(entity: BaseEntity, ctx: ValidationContext): ValidationIssue[] {
    if (entity.id.startsWith('PLACE_') && isPlace(entity)) {
      return validateVesselCrew(entity, ctx);
    }
    return [];
  },
};
