/**
 * Core types used throughout the codebase.
 * Foundational types with minimal dependencies.
 */

import type { TilemapData } from '../world/place-layout.js';

/**
 * Entity IDs follow a strict prefix convention for type safety and debugging:
 *
 * - **CHAR_** - Character entities (e.g., `CHAR_aldric`, `CHAR_veteran_tom`)
 * - **PLACE_** - Place entities (e.g., `PLACE_tavern`, `PLACE_market_square`)
 * - **OBJ_** - Object entities for scenery/obstacles/exits (e.g., `OBJ_oak_tree`, `OBJ_exit_tavern_door`)
 *
 * ID Format:
 * - Prefix is UPPERCASE with underscore separator
 * - Suffix is lowercase with underscores (slug format)
 * - Example: `CHAR_mysterious_stranger`, `PLACE_ancient_ruins`
 *
 * Generation:
 * - New entity IDs are generated by services/core/universe-store.ts
 * - Characters: `generateCharacterId(name)` → `CHAR_{slugified_name}`
 * - Places: `generatePlaceId(name)` → `PLACE_{slugified_name}`
 * - Objects/Exits: Manual creation, typically `OBJ_{descriptive_name}` or `OBJ_exit_{name}`
 *
 * Validation helpers:
 * - `id.startsWith('CHAR_')` to check if entity is a character
 * - `id.startsWith('PLACE_')` to check if entity is a place
 * - `id.startsWith('OBJ_')` to check if entity is an object
 */

/**
 * Distance units from small to cosmic scale.
 * Used for place dimensions and position coordinates.
 */
export type DistanceUnit =
  | 'feet' // Indoor spaces, small outdoor areas
  | 'meters' // Metric alternative
  | 'miles' // Regions, wilderness, seas
  | 'kilometers' // Metric alternative
  | 'au' // Astronomical units (solar system scale)
  | 'lightyears'; // Interstellar/galactic scale

/** Const array for schema enum usage - derived from DistanceUnit type. */
export const DISTANCE_UNITS = [
  'feet',
  'meters',
  'miles',
  'kilometers',
  'au',
  'lightyears',
] as const;

/**
 * Unified position and spatial data for all entities.
 * Coordinates are relative to the parent place, using the parent's scale unit.
 * All entities MUST have valid x/y coordinates - use center of parent if unknown.
 *
 * Key insight: Position coordinates use the PARENT's scale, not the entity's own scale.
 * A tavern at { x: 0.75, y: 1.15, parent: "PLACE_city" } is 0.75 miles from city origin
 * if the city's scale is 'miles', even though the tavern's own scale is 'feet'.
 *
 * Place dimensions (two distinct concepts):
 * - **width, height**: Size when the place is rendered as an object in its parent (from slot at
 *   creation, or from layout for root). Objects use width/height for collision bounds (in parent's scale).
 * - **innerWidth, innerHeight**: Playable area inside the place (from layout). Used for game room
 *   bounds, character movement, object placement.
 */
export interface Position {
  /** X coordinate relative to parent (in parent's scale unit) */
  x: number;
  /** Y coordinate relative to parent (in parent's scale unit) */
  y: number;
  /** Parent place ID, null only for root (cosmos) */
  parent: string | null;

  // ---- Spatial Dimensions ----

  /** For places: size when rendered as object in parent. For objects: collision bounds in parent's scale. */
  width: number;
  /** For places: size when rendered as object in parent. For objects: collision bounds in parent's scale. */
  height: number;

  /** Place only: playable area inside the place (from layout). */
  innerWidth?: number;
  /** Place only: playable area inside the place (from layout). */
  innerHeight?: number;
}

/**
 * Constrained relationship types between characters.
 * Prevents hallucinated types like "potential_childhood_acquaintance".
 */
export const RELATIONSHIP_TYPES = [
  'stranger',
  'acquaintance',
  'colleague',
  'friend',
  'rival',
  'enemy',
  'family',
  'romantic',
  'mentor',
  'subordinate',
  'superior',
] as const;

export type RelationshipType = (typeof RELATIONSHIP_TYPES)[number];

/** Runtime type guard for RelationshipType. */
export function isRelationshipType(value: string): value is RelationshipType {
  return (RELATIONSHIP_TYPES as readonly string[]).includes(value);
}

/**
 * A structured relationship between a character and another entity (character or place).
 *
 * For characters: tracks interpersonal dynamics (type, disposition).
 * For places: tracks awareness and visit state (via familiarity thresholds).
 *
 * Familiarity thresholds:
 * - 0-19: Stranger (characters) / Unaware (places)
 * - 20-49: Knows name (characters) / Heard of but not visited (places)
 * - 50+: Well-known (characters) / Has visited (places)
 */
export interface CharacterRelationship {
  /** The entity ID this relationship is with (CHAR_xxx or PLACE_xxx) */
  targetId: string;
  /** Nature of the connection (characters only, null for places) */
  type: RelationshipType | null;
  /** Sentiment score: -100 (hatred) to +100 (devotion). Only meaningful for characters. */
  disposition: number | null;
  /** How well they know this entity: 0-100. >= 20 = aware/known, >= 50 = visited (places) */
  familiarity: number;
  /** Brief note about this relationship or how they know this place */
  context: string | null;
  /** True if place needs to be generated (places only, awaiting lazy generation) */
  pendingGeneration: boolean;
}

export type EntityType = 'character' | 'place' | 'event' | 'object';

/**
 * Reason for a location update broadcast.
 * Used by the WebSocket service to communicate why clients should refresh.
 */
export type LocationUpdateReason =
  | 'movement'
  | 'mapUpdated'
  | 'imageUpdated'
  | 'nameReveal'
  | 'placeReveal'
  | 'placeGenerated'
  | 'characterGenerated'
  | 'placeAliasAdded'
  | 'vessel_movement'
  | 'journey_started'
  | 'journey_arrived'
  | 'journey_cancelled'
  | 'travel_arrived'
  | 'equipment_change'
  | 'item_pickup'
  | 'item_drop'
  | 'wait';

/**
 * Discriminated union of background job payloads.
 * Used by the background queue service to type-check job data.
 */
export type BackgroundJobPayload =
  | {
      type: 'image_generation';
      data: { entityId: string; entityType: 'character' | 'place'; purpose?: string };
    }
  | { type: 'routine_generation'; data: { characterId: string; creationPlaceId?: string } }
  | {
      type: 'tag_update';
      data: { entityId: string; entityType: 'character' | 'place'; currentPlaceId?: string };
    }
  | {
      type: 'slot_population';
      data: { placeId: string; slotCount: number };
    }
  | {
      type: 'place_generation';
      data: {
        /** Parent place where the new place will be created */
        parentPlaceId: string;
        /** Purpose of the place to generate (e.g. 'bedroom', 'residence') */
        purpose: string;
        /** Human-readable reason for generation (for logging) */
        reason: string;
      };
    };

export interface TagDefinition {
  tagId: string;
  label: string;
  description: string | null;
}

/** Marker category for minimap rendering and visibility toggling. */
export type MinimapMarkerType = 'player' | 'npc' | 'place' | 'exit' | 'object';

/** A marker on the minimap representing an entity in the place. */
export interface MinimapMarker {
  id: string;
  label: string;
  /** Normalized position (0-1) within the place */
  x: number;
  /** Normalized position (0-1) within the place */
  y: number;
  /** Marker category for visual styling and visibility toggling */
  type: MinimapMarkerType;
  /** Purpose or interaction type for future sub-filtering (e.g. "vessel_helm", "exit"). Null if not applicable. */
  subtype: string | null;
}

/** Complete data for rendering a minimap. Returned by the minimap endpoint. */
export interface MinimapData {
  /** Current place name */
  placeName: string;
  /** Current place ID */
  placeId: string;
  /** Parent place ID (for zoom-out), null if root */
  parentId: string | null;
  /** Place environment type */
  environment: string;
  /** Player position normalized 0-1, null if not positionable */
  player: { x: number; y: number } | null;
  /** Markers for child places and exits, all normalized 0-1 */
  markers: MinimapMarker[];
  /** Weather condition, null when environment has no atmospheric weather */
  weather: string | null;
  /** Season name, null if not applicable */
  season: string | null;
  /** Temperature in degrees, null if not applicable */
  temperature: number | null;
  /** Temperature band, null if not applicable */
  temperatureBand: string | null;
  /** Formatted game time string (e.g., "14:30"), null if no calendar */
  time: string | null;
  /** Tilemap data for canvas rendering, null if no layout */
  tilemap: TilemapData | null;
}

/**
 * A feature layer entry for a race or sprite archetype.
 * Describes one optional visual feature (ears, nose, eyes, facial hair, etc.)
 * with available styles, generation probability, and player-selection rules.
 *
 * The sprite helper iterates these generically — it doesn't hardcode knowledge
 * of specific feature types. Adding a new feature type (wings, tails, horns)
 * requires only adding an entry here plus assets in the manifest.
 */
export interface RaceFeatureLayer {
  /** Manifest layer type (e.g., "ears", "nose", "eyes", or any future layer). */
  layerType: string;
  /** Available style IDs to choose from (e.g., ["elvenears"] or ["buttonnose", "bignose"]). */
  styles: string[];
  /** Probability 0-1 that this feature is included during auto-generation (1.0 = always). */
  chance: number;
  /** If true, exposed in the character creator for manual selection. */
  playerSelectable: boolean;
}

/** Non-empty array helper type. */
export type NonEmptyArray<T> = [T, ...T[]];

/**
 * Sprite generation hints for a race.
 * Used to map races to appropriate LPC sprite assets.
 */
export type RaceSpriteHints = HumanoidRaceSpriteHints | NonHumanoidRaceSpriteHints;

/** Sprite hints for races with humanoid body support. */
export interface HumanoidRaceSpriteHints {
  /** True for humanoid races that render with LPC body/head layers. */
  humanoidBody: true;
  /** Sprite archetype ID from the archetype registry (e.g., 'human', 'orc', 'wolf'). */
  spriteArchetype: string;
  /** Default skin color when generating characters of this race (v3 SkinColor value). */
  defaultSkinColor: string;
  /** Explicit allowed skin colors for this race (non-empty). */
  allowedSkinColors: NonEmptyArray<string>;
  /** Allowed eye colors for this race (empty/null = all allowed). */
  allowedEyeColors: string[] | null;
  /** Allowed hair colors for this race (null = all allowed from HAIR_COLORS). */
  allowedHairColors: string[] | null;
  /** Visual scale multiplier for this race (default 1.0). Composes with per-layout characterScale. */
  spriteScale: number;
  /** Override archetype featureLayers for this race (null = use archetype defaults). */
  featureLayers: RaceFeatureLayer[] | null;
}

/** Sprite hints for non-humanoid races (portrait-only/no body sprite). */
export interface NonHumanoidRaceSpriteHints {
  /** False for non-humanoid races that do not use LPC body/head sprites. */
  humanoidBody: false;
  /** Non-humanoid races do not use sprite archetypes. */
  spriteArchetype: null;
  /** Non-humanoid races do not use skin tint defaults. */
  defaultSkinColor: null;
  /** Non-humanoid races do not use skin tint palettes. */
  allowedSkinColors: null;
  /** Allowed eye colors for this race (empty/null = all allowed). */
  allowedEyeColors: string[] | null;
  /** Allowed hair colors for this race (null = all allowed from HAIR_COLORS). */
  allowedHairColors: string[] | null;
  /** Visual scale multiplier for this race (default 1.0). */
  spriteScale: number;
  /** Override archetype featureLayers for this race (null = use archetype defaults). */
  featureLayers: RaceFeatureLayer[] | null;
}

export interface RaceDefinition {
  id: string;
  label: string;
  description: string;
  rarity: 'rare' | 'uncommon' | 'common';
  /** Sprite generation hints for character appearance. */
  spriteHints: RaceSpriteHints | null;
}
