/**
 * Storyteller types for narrative orchestration.
 */

import type { PlotState, TriggerCondition } from './plot.js';

/**
 * Range for randomizing plotStartDelay on generated plots.
 */
export interface PlotStartDelayRange {
  /** Minimum hours before opening event fires (default: 0) */
  min: number;
  /** Maximum hours before opening event fires (default: 4) */
  max: number;
}

/**
 * Story arc structure configuration.
 */
export interface StorytellerArcStructure {
  /** Number of major story acts */
  acts: number;
  /** How progress builds over time */
  tensionCurve: 'rising' | 'episodic' | 'wave' | 'building';
}

/**
 * Global storyteller definition template.
 * Stored in storytellers/definitions/ with ID format STORYTELLER_{snake_case_label}
 */
export interface StorytellerDefinition {
  id: string; // e.g., "STORYTELLER_classic_adventure"
  label: string; // e.g., "Classic Adventure"
  description: string; // Description for UI selection

  // Narrative configuration
  pacing: 'very-fast' | 'fast' | 'moderate' | 'slow';
  eventTypes: string[]; // Types of events this storyteller generates

  // Story arc configuration
  arcStructure: StorytellerArcStructure;

  /**
   * Story style guidance that influences arbiter decisions and plot generation.
   * Describes what kinds of events happen, NPC behaviors, stakes, complications.
   *
   * Examples:
   * - "Romantic encounters arise naturally, emotional stakes take precedence over physical danger"
   * - "Threats are lethal, escape routes are scarce, NPCs harbor secrets and hidden agendas"
   */
  storyStyle: string;

  /**
   * Narrative tone/mood for prose style (how events are described).
   * Short descriptor that colors all narration.
   *
   * Examples: "horror", "romantic", "whimsical", "grimdark", "comedic", "noir", "action"
   */
  tone: string;

  // Plot management
  /** How many active plots to maintain (default: 2) */
  targetPlotCount: number | null;
  /** Max concurrent plot generations (default: 1) */
  maxPendingPlots: number | null;
  /** Range for randomizing plotStartDelay on generated plots */
  plotStartDelayRange: PlotStartDelayRange | null;

  image: string | null;

  // Verbosity control
  /** Response verbosity level 1-5 (defaults to 3). Controls narration and NPC dialog length. */
  verbosity: number | null;

  // Stagnation thresholds
  /** Consecutive travel inputs before stagnation intervention (default: 6) */
  travelStagnationThreshold: number | null;

  // Voice configuration
  /** Default TTS voice registry ID for NPC dialog and narration. Copied to instance state when selected. */
  voiceId: string;
}

/**
 * An event generated by the storyteller.
 */
export interface StorytellerEvent {
  id: string;
  type: string; // e.g., "rumor", "arrival", "discovery", "confrontation"
  description: string; // What happened
  timestamp: string; // In-universe date
  affectedEntities: string[]; // Entity IDs involved
  arcId: string | null;

  // Context for future event planning
  placeId: string | null; // Where the event occurred (place ID)
  sceneSummary: string | null; // Brief summary of what happened (e.g., "Heard a rumor about missing merchants from a local sailor")
  charactersPresent: string[] | null; // Characters nearby when event occurred (labels, not IDs)
}

/**
 * Per-character storyteller instance state.
 * Stored on CharacterInfo.storytellerState for player characters.
 * Supports multiple concurrent plots with progress-driven events.
 */
export interface StorytellerInstanceState {
  /** Reference to the storyteller definition */
  storytellerId: string;

  // Voice configuration
  /** TTS voice registry ID for NPC dialog and narration. Initialized from definition, can be customized per-game. */
  voiceId: string;

  // Multi-plot state
  /** Currently active plots */
  activePlots: PlotState[];
  /** Whether plot generation is in progress */
  generationInProgress: boolean;

  // Event tracking
  /** Historical events for debugging/continuity */
  eventHistory: StorytellerEvent[];

  // Timing
  /** When the storyteller was selected (for debugging) */
  storytellerSelectedAt: string;

  // Custom state (storyteller-specific data)
  custom: Record<string, unknown>;
}

/**
 * Stagnation status for admin display.
 */
export interface StagnationStatus {
  /** Whether the narrative is currently stagnant */
  isStagnant: boolean;
  /** Type of stagnation detected */
  type: 'none' | 'waiting' | 'travel';
  /** Number of consecutive turns in stagnant pattern */
  consecutiveTurns: number;
  /** Number of travel turns before stagnation triggers (default: 6) */
  travelThreshold: number;
  /** Number of waiting turns before stagnation triggers (default: 2) */
  waitingThreshold: number;
}

/**
 * Player intent extracted from recent actions during stagnation.
 * Used to determine appropriate resolution strategy.
 */
export interface PlayerIntent {
  /** Type of intent detected */
  type: 'destination' | 'waiting_for' | 'activity' | 'unknown';
  /** Resolved entity ID (e.g., place ID for destination) */
  target: string | null;
  /** Player's own words for the target (e.g., "the tavern") */
  targetRef: string | null;
  /** Confidence in the extracted intent */
  confidence: 'high' | 'medium' | 'low';
}

/**
 * Context about plot progress for stagnation resolution decisions.
 * Determines whether forcing resolution would skip turning points.
 */
export interface PlotProgressContext {
  /** Current progress level of the primary plot */
  currentProgress: number;
  /** Progress target of the next unfired turning point */
  nextTurningPointProgress: number | null;
  /** Gap between current progress and next turning point (0 if none) */
  progressGap: number;
  /** Whether there are unfired turning points remaining */
  hasUnfiredTurningPoints: boolean;
  /** Recommended action based on progress gap analysis */
  recommendedAction: 'fire_event' | 'allow_resolution';
}

/**
 * Summary of a turning point for admin display.
 */
export interface TurningPointSummary {
  /** Unique identifier for this turning point */
  id: string;
  /** Brief description of what happens */
  description: string;
  /** Story progress threshold when this might trigger (0-100) */
  progressTarget: number;
  /** Whether this turning point has been triggered */
  triggered: boolean;
  /** Game date when triggered (if triggered) */
  triggeredAt: string | null;
  /** Trigger conditions that must be met before this TP can fire */
  triggerConditions: TriggerCondition[] | null;
  /** Game date when all non-condition requirements were first met (deferral tracking) */
  conditionsEligibleSince: string | null;
}

/**
 * Goal summary for admin status display.
 */
export interface GoalSummary {
  /** Goal identifier */
  id: string;
  /** Natural language description of the goal */
  description: string;
  /** Whether this goal has been achieved */
  isAchieved: boolean;
  /** Whether this goal has failed */
  isFailed: boolean;
  /** Progress boost when achieved or failed */
  progressBoost: number;
  /** Whether this goal is hidden from the player (for admin display) */
  isHidden: boolean;
}

/**
 * Summary of an active plot for admin display.
 */
export interface PlotStatusSummary {
  /** Unique instance ID for this plot */
  id: string;
  /** Truncated plot description for display */
  plotSummary: string;
  /** Current story progress (0-100) */
  progressLevel: number;
  /** Story flags accumulated for this plot */
  storyFlags: string[];
  /** Goals with achievement status */
  goals: GoalSummary[];
  /** All turning points with triggered status */
  turningPoints: TurningPointSummary[];
  /** Next event timing (game date) */
  nextEventAt: string | null;
}

/**
 * Response from GET /api/universes/:universeId/characters/:characterId/storyteller/status
 * Provides computed status data for admin monitoring.
 */
export interface StorytellerStatusResponse {
  /** Current stagnation detection status (computed from messages) */
  stagnation: StagnationStatus;
  /** Active plots with summary data */
  activePlots: PlotStatusSummary[];
  /** Whether a plot generation is currently in progress */
  generationInProgress: boolean;
  /** Number of completed plots */
  completedPlotCount: number;
  /** The storyteller definition label (for display) */
  storytellerLabel: string | null;
}
